--- #YAML:1.0
name:               WWW-Scraper-ISBN-ISBNdb_Driver
version:            0.05
abstract:           isbndb.com driver for WWW::Scraper::ISBN
author:
    - David J. Iberri <diberri@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    WWW::Scraper::ISBN:   0
    WWW::Scraper::ISBN::Driver:  0.15
    XML::DOM:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
