--- #YAML:1.0
name:               WWW-Scraper-ISBN-ISBNdb_Driver
version:            0.09
abstract:           Search driver for the isbndb.com online book catalog
author:
  - David J. Iberri <diberri@cpan.org>
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

configure_requires:
  ExtUtils::MakeMaker:          0
requires:
  perl:                         5.006
  IO::File:                     0
  LWP::UserAgent:               0
  WWW::Scraper::ISBN:           0.25
  WWW::Scraper::ISBN::Driver:   0.18
  XML::DOM:                     0
  XML::LibXML:                  0
recommends:
  Test::CPAN::Meta:             0
  Test::CPAN::Meta::JSON:       0
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
build_requires:
  Test::More:                   0.70

provides:
  WWW::Scraper::ISBN::ISBNdb_Driver:
    file:     lib/WWW/Scraper/ISBN/ISBNdb_Driver.pm
    version:  0.09

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Scraper-ISBN-ISBNdb_Driver
  repository: http://github.com/barbie/www-scraper-isbn-isbndb_driver

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
