# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN-ISBNdb_Driver
version:      0.04
version_from: lib/WWW/Scraper/ISBN/ISBNdb_Driver.pm
installdirs:  site
requires:
    Test::More:                    0
    WWW::Scraper::ISBN::Driver:    0.15
    XML::DOM:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
